#!./guile
!# ;; -*-scheme-*-

;;; Copyright (C) 2019 Rob Browning <rlb@defaultvalue.org>
;;; SPDX-License-Identifier: LGPL-2.1-or-later OR EPL-1.0+

(use-modules
 ((lokke scm test-anything) #:select (tap-test-runner))
 ((lokke core) #:prefix t/)
 ((srfi srfi-64)
  #:select (test-assert
            test-begin
            test-end
            test-eq
            test-equal
            test-eqv
            test-group
            test-runner-current
            test-runner-fail-count)))

(when (equal? "tap" (getenv "LOKKE_TEST_PROTOCOL"))
  (test-runner-current (tap-test-runner)))

(test-begin (basename (car (program-arguments))))

(test-equal #t (t/distinct?))
(test-equal #t (t/distinct? 1))
(test-equal #t (t/distinct? 1 2 3))
(test-equal #f (t/distinct? 1 1))
(test-equal #f (t/distinct? 1 2 3 2))
(test-equal #f (t/distinct? 1 2 3 2 4))

(test-end)

(unless (zero? (test-runner-fail-count (test-runner-current)))
  (exit 2))
