#!./guile
!# ;; -*-scheme-*-

;;; Copyright (C) 2019 Rob Browning <rlb@defaultvalue.org>
;;; SPDX-License-Identifier: LGPL-2.1-or-later OR EPL-1.0+

(use-modules
 ((lokke scm test-anything) #:select (tap-test-runner))
 ((lokke ns) #:prefix t/)
 ((lokke pr) #:select (*out*))
 ((srfi srfi-64)
  #:select (test-assert
            test-begin
            test-end
            test-equal
            test-group
            test-runner-current
            test-runner-fail-count)))

(when (equal? "tap" (getenv "LOKKE_TEST_PROTOCOL"))
  (test-runner-current (tap-test-runner)))

(test-begin (basename (car (program-arguments))))

;; FIXME: no error tests (well nearly no tests at all, really)

(test-equal "x/y" ((module-ref (t/resolve-ns 'clojure.string) 'join)
                   "/" '("x" "y")))

(test-equal 'clojure.core (t/ns-name (resolve-module '(lokke ns clojure core))))
(test-equal 'guile.srfi.srfi-1 (t/ns-name (resolve-module '(srfi srfi-1))))

(test-end)

(unless (zero? (test-runner-fail-count (test-runner-current)))
  (exit 2))
