#!/usr/bin/env bash

set -uxeo pipefail

exit_rm_paths=()

on_exit()
{
    if test "${#exit_rm_paths[@]}" -gt 0; then
        rm -rf "${exit_rm_paths[@]}"
    fi
}
trap on_exit EXIT

if test -z "${LOKKE_TEST_EXT_BEHAVIOR:-}"; then
    echo '1..0 # skip standalone-install tests (LOKKE_TEST_EXT_BEHAVIOR unset)'
    exit 0
fi

dirty_tree=$(git status --porcelain -uno)
if test "$dirty_tree"; then
    echo 'Bail out! standalone-install tests detected uncommitted changes'
    exit 2
fi

echo '1..2'

test -f test/standalone-install
mkdir -p test/tmp
tmpdir=$(mktemp -d "test/tmp/test-standalone-install-XXXXXX")
tmpdir=$(cd "$tmpdir" && pwd)
exit_rm_paths+="$tmpdir"

git clone . "$tmpdir/lokke"
cd "$tmpdir/lokke"
./setup
autoreconf -fi
./configure --prefix=$(pwd)/../install
make -j2 install
cd /

i=0

check-cmd()
(
    result=$("$@")
    rc=$?
    if test $rc -eq 0 && test "$result" = ':howdy'; then
        echo 'ok $i'
    else
        echo "not ok $i ($rc) $@ => $result"
    fi
    ((i++)) || true
)

check-cmd "$tmpdir/install/bin/lok" -e '(println :howdy)'
check-cmd "$tmpdir/install/bin/lokke" run -e '(println :howdy)'
