;;; Copyright (C) 2019 Rob Browning <rlb@defaultvalue.org>
;;;
;;; This project is free software; you can redistribute it and/or
;;; modify it under the terms of (at your option) either of the
;;; following two licences:
;;;
;;;   1) The GNU Lesser General Public License as published by the
;;;      Free Software Foundation; either version 2.1, or (at your
;;;      option) any later version
;;;
;;;   2) The Eclipse Public License; either version 1.0 or (at your
;;;      option) any later version.

;; This is the lowest level, supporting *everything*, including
;; definitions required by code generated by the compiler, etc., and
;; providing bits needed to bootstrap the system by compiling
;; clojure.core, i.e. (lokke ns clojure core).

(define-module (lokke boot)
  #:use-module ((lokke ns) #:select (ns))
  #:export (/lokke/reader-hash-map
            /lokke/reader-hash-set
            /lokke/reader-vector
            syntax-quote)
  #:re-export (ns quasiquote quote unquote unquote-splicing)
  #:duplicates (merge-generics replace warn-override-core warn last))

(define-syntax-rule (syntax-quote form)
  (quasiquote form))

(define-syntax-rule (/lokke/reader-hash-map x ...)
  ((@ (lokke hash-map) hash-map) x ...))

(define-syntax-rule (/lokke/reader-hash-set x ...)
  ((@ (lokke hash-set) hash-set) x ...))

(define-syntax-rule (/lokke/reader-vector x ...)
  ((@ (lokke vector) vector) x ...))
